// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | "/"
    | "/assets/archive-and-restore.gif"
    | "/assets/brand-logo.png"
    | "/assets/flowchart.png"
    | "/assets/icons/icon-16.png"
    | "/assets/icons/icon-64.png"
    | "/assets/icons/tabs.png"
    | "/assets/list-grid-views.gif"
    | "/assets/move-tab-to-space.gif"
    | "/assets/sort-tabs.gif"
    | "/assets/sync-tabs.gif"
    | "/assets/webtime-chart.gif"
    | "/background.js"
    | "/main.js"
    | "/manifest.json"
    | "/vite-env.js"
    | "/vite.svg"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
